project_id = "ymvvokvfrwmnabmcmsrm"

[functions.webhook]
verify_jwt = false

[functions.send-message]
verify_jwt = true

[functions.evolution-webhook]
verify_jwt = false

[functions.list-evolution-instances]
verify_jwt = false