// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymvvokvfrwmnabmcmsrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdnZva3ZmcndtbmFibWNtc3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjM2MjcsImV4cCI6MjA2OTM5OTYyN30.ws1r6FSsJ2p7sJLjAeCNxJSch_nwwm66vi5YBWS-naI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});